#' Plot the mean arrival age of species in an assemblage based in an ancestral area reconstruction across geographic space
#'
#' @param age_arrival_comm A list of length two generated by
#'   \code{\link{Herodotools::calc_age_arrival}} containing community-level
#'    mean arrival age of species in an assemblage based in an ancestral area 
#'    reconstruction.
#'
#' @param coords A rectangular object (it can be a matrix, data.frame or tibble)
#'     containing two columns, one with longitude and another with latitude
#'     coordinates in this order.
#'
#' @param shapefile An \code{sf} object containing the geographic boundaries to
#'   be overlaid on the raster map (e.g., continents, biogeographic regions, or
#'   study area limits).
#'
#' @param color_palette character string specifying the color palette to be used for
#'   quantitative variables in \code{rcartocolor::scale_fill_carto_c}.
#'
#' @return A \code{ggplot2} object is returned.
#'
#' @examples
#' \dontrun{
#'
#' # Compute diversification metrics
#'
#' akodon_age_comm <- Herodotools::calc_age_arrival(W = akodon_pa_tree,
#'                                          tree = akodon_newick,
#'                                          ancestral.area = node_area,
#'                                          biogeo = biogeo_area)
#' #Load data
#'
#' site_xy <- akodon_sites |>
#'     dplyr::select(LONG, LAT)
#'
#' coastline <- rnaturalearth::ne_coastline(returnclass = "sf")
#'
#' coastline_crop <- sf::st_crop(coastline,
#'                           xmin = map_limits$x[1],
#'                           xmax = map_limits$x[2],
#'                           ymin = map_limits$y[1],
#'                           ymax = map_limits$y[2])
#'
#'
#' plot_age_arrival(age_arrival_comm = akodon_age_comm,
#'                  coords = site_xy,
#'                  shapefile = coastline_crop)
#'
#' }
#'
#' @author Maria Gabriela Junqueira and Gabriel Nakamura
#'
#' @export


plot_age_arrival <- function(age_arrival_comm,
                             coords,
                             shapefile,
                             color_palette = "SunsetDark") {

  # step 1 - checks for coords ----
  if (!is.data.frame(coords)) {
    stop("coords must be a data.frame or tibble with longitude and latitude.")
  }

  if (ncol(coords) < 2) {
    stop("coords must have at least two columns.")
  }

  lon_names <- c("LONG", "lon", "longitude", "x")
  lat_names <- c("LAT", "lat", "latitude", "y")

  col1 <- names(coords)[1]
  col2 <- names(coords)[2]

  if (!col1 %in% lon_names | !col2 %in% lat_names) {
    stop("The first column of coords must be longitude and the second latitude.")
  }

  coords <- dplyr::rename(
    coords,
    LONG = !!col1,
    LAT  = !!col2
  )

  # step 2 - build dataframe ----
  df_sites <- dplyr::bind_cols(coords,
                               mean_age_arrival = age_arrival_comm$mean_age_per_assemblage)

  # step 3 - output ----
  ggplot2::ggplot(df_sites) +
    ggplot2::geom_raster(
      aes(x = LONG, y = LAT, fill = mean_age_arrival)
    ) +
    rcartocolor::scale_fill_carto_c(
      type = "quantitative",
      palette = color_palette,
      direction = 1,
      limits = c(0, 3.5),
      breaks = seq(0, 3.5, by = .5),
      labels = glue::glue("{seq(0, 3.5, by = 0.5)}"))  +
    ggplot2::geom_sf(
      data = shapefile,
      fill = NA,
      color = "black",
      linewidth = 0.7
    ) +
    ggplot2::guides(fill = guide_colorbar(barheight = unit(50, units = "mm"),
                                          barwidth = unit(2.5, units = "mm"),
                                          direction = "vertical",
                                          ticks.colour = "#ffffff",
                                          title.position = "top",
                                          title.hjust = 0.5)) +
    ggplot2::theme_bw() +
    ggplot2::xlab("\nLongitude") +
    ggplot2::ylab("Latitude\n") +
    ggplot2::labs(fill = "Mean arrival age (Myr)\n") +
    ggplot2::theme(
      panel.grid.major = element_line(linetype = "dashed",
                                      lineend = "round"),
      axis.title = element_blank(),
      axis.text.y = element_text(angle = 90, hjust = .45)
    )
}