#' Plot historical dispersal contribution from source areas
#'
#' This function plots spatial patterns of historical dispersal contribution from
#'     one or multiple source areas. The user can visualize a single area 
#'     or multiple areas simultaneously using \code{facet_wrap()}.
#'
#' When multiple areas are plotted, the order of the facets follows
#' the order of the columns provided in \code{area_cols}, not alphabetical order.
#'
#'
#' @param dispersal_from A data.frame generated by \code{\link{calc_dispersal_from}}  
#'     where each column represents dispersal contribution from a source area, 
#'     and each row corresponds to a spatial cell
#'
#' @param coords A rectangular object (it can be a matrix, data.frame or tibble)
#'     containing two columns, one with longitude and another with latitude
#'     coordinates in this order.
#'
#' @param shapefile An \code{sf} object containing the geographic boundaries to
#'   be overlaid on the raster map (e.g., continents, biogeographic regions, or
#'   study area limits).
#'
#' @param area_cols Integer vector indicating which columns of
#'   \code{dispersal_from} should be used (plural).
#'   If \code{NULL} (default), all columns are used.
#'
#' @param area_col Integer indicating a single column of \code{dispersal_from}
#'   to be plotted (singular). This argument is only used when
#'   \code{facet = FALSE} and must be one of the values provided in
#'   \code{area_cols}.
#'
#' @param color_palette character string specifying the color palette to be used for
#'   quantitative variables in \code{rcartocolor::scale_fill_carto_c}. Ignored
#'   for \code{"DR_prop"}, which uses a fixed palette and scale. Default is "SunsetDark"
#'
#' @param facet Logical. If \code{TRUE}, all areas defined in
#'   \code{area_cols} are plotted using \code{facet_wrap()}.
#'   If \code{FALSE}, a single area defined by \code{area_col} is plotted.
#'
#' @details
#' The function assumes that \code{dispersal_from} and \code{coords}
#' have the same number of rows and are ordered consistently.
#'
#' All area selections are performed using numeric column indices,
#' ensuring an unambiguous mapping to the original columns of
#' \code{dispersal_from}.
#'
#' @return A \code{ggplot} object.
#'
#' \dontrun{
#'
#' # Compute dispersal
#'
#' akodon_dispersal <-  Herodotools::calc_dispersal_from(W = akodon_pa_tree,
#'                                  tree = akodon_newick,
#'                                  ancestral.area = node_area,
#'                                  biogeo = biogeo_area)
#'
#' #Load data
#'
#' site_xy <- akodon_sites |>
#'     dplyr::select(LONG, LAT)
#'
#' coastline <- rnaturalearth::ne_coastline(returnclass = "sf")
#'
#' coastline_crop <- sf::st_crop(coastline,
#'                           xmin = map_limits$x[1],
#'                           xmax = map_limits$x[2],
#'                           ymin = map_limits$y[1],
#'                           ymax = map_limits$y[2])
#'
#' #Single map
#'
#' plot_dispersal_from(dispersal_from = akodon_dispersal,
#'                     coords = site_xy,
#'                     shapefile = coastline_crop,
#'                     area_col = 1,
#'                     facet = FALSE)
#'
#' #Multiple maps
#'
#' plot_dispersal_from(dispersal_from = akodon_dispersal,
#'                     coords = site_xy,
#'                     shapefile = coastline_crop,
#'                     area_cols = c(1, 3, 5),
#'                     facet = TRUE)
#'
#' #All maps
#'
#' plot_dispersal_from(akodon_dispersal,
#'                     coords = site_xy,
#'                     shapefile = coastline_crop,
#'                     facet = TRUE)
#'
#' #' }
#'
#' @author Maria Gabriela Junqueira and Gabriel Nakamura
#'
#' @export
#'

plot_dispersal_from <- function(dispersal_from,
                                  coords,
                                  shapefile,
                                  area_cols = NULL,
                                  area_col  = NULL,
                                  color_palette = "SunsetDark",
                                  facet = FALSE) {

  # step 1 - checks for coords ----
  if (!is.data.frame(coords) || ncol(coords) < 2) {
    stop("coords must be a data.frame with longitude and latitude.")
  }

  lon_names <- c("LONG", "lon", "longitude", "x")
  lat_names <- c("LAT", "lat", "latitude", "y")

  col1 <- names(coords)[1]
  col2 <- names(coords)[2]

  if (!col1 %in% lon_names | !col2 %in% lat_names) {
    stop("The first column of coords must be longitude and the second latitude.")
  }

  coords <- dplyr::rename(coords, LONG = !!col1, LAT = !!col2)

  # step 2 - select columns (areas == evoregions) ----
  if (is.null(area_cols)) {
    area_cols <- seq_len(ncol(dispersal_from))
  }

  if (!is.numeric(area_cols)) {
    stop("'area_cols' must be numeric column indices.")
  }

  if (any(area_cols < 1) || any(area_cols > ncol(dispersal_from))) {
    stop("Invalid values in 'area_cols'.")
  }

  # step 3 - single area check ----
  if (!facet) {

    if (is.null(area_col)) {
      stop("When facet = FALSE, you must provide 'area_col'.")
    }

    if (!is.numeric(area_col) || length(area_col) != 1) {
      stop("'area_col' must be a single numeric column index.")
    }

    if (!area_col %in% area_cols) {
      stop("'area_col' must be one of 'area_cols'.")
    }

    area_cols <- area_col
  }

  dispersal_sel <- dispersal_from[, area_cols, drop = FALSE]

  # step 4 -build dataframe ----
  df_sites <- dplyr::bind_cols(coords, dispersal_sel) |>
    tidyr::pivot_longer(
      cols      = -c(1, 2),
      names_to  = "evoregions",
      values_to = "dispersal"
    )

  # step 4.1 - Fix order of facets ----
  df_sites$evoregions <- factor(
    df_sites$evoregions,
    levels = colnames(dispersal_sel)
  )

  # step 5 - plotting ----
  p <- ggplot2::ggplot(df_sites) +
    ggplot2::geom_raster(
      ggplot2::aes(
        x    = LONG,
        y    = LAT,
        fill = dispersal
      )
    ) +
    rcartocolor::scale_fill_carto_c(
      type     = "quantitative",
      palette = color_palette,
      na.value = "transparent",
      limits  = c(0, 1)
    ) +
    ggplot2::geom_sf(
      data      = shapefile,
      fill      = NA,
      color     = "black",
      linewidth = 0.7
    ) +
    ggplot2::labs(fill = "Contribution\n") +
    ggplot2::guides(
      fill = ggplot2::guide_colorbar(
        barheight = grid::unit(50, "mm"),
        barwidth  = grid::unit(2.5, "mm"),
        direction = "vertical",
        ticks.colour = "#ffffff",
        title.position = "top",
        title.hjust = 0.5
      )) +
    ggplot2::theme_bw() +
    ggplot2::theme(
      panel.grid.major = ggplot2::element_line(
        linetype = "dashed",
        lineend = "round"
      ),
      axis.title = ggplot2::element_blank(),
      axis.text.y = ggplot2::element_text(angle = 90, hjust = 0.45)
    )

  if (facet) {
    p <- p +
      ggplot2::facet_wrap(
        ~ evoregions,
        labeller = ggplot2::labeller(
          evoregions = function(x) paste("From", x)
        )
      ) +
      ggplot2::theme(
        strip.background = ggplot2::element_blank(),
        strip.text = ggplot2::element_text(
          size  = 12,
          face  = "bold",
          hjust = 0
        ),
        panel.grid.major = ggplot2::element_line(
          linetype = "dashed",
          lineend = "round"
        )
      )
  }

  return(p)
}














