#' Plot the evoregions
#'
#' @param evoregions A list generated by
#'   \code{\link{Herodotools::calc_evoregions}}
#'
#' @param coords A rectangular object (it can be a matrix, data.frame or tibble)
#'     containing two columns, one with longitude and another with latitude
#'     coordinates in this order.
#'
#' @param shapefile An \code{sf} object containing the geographic boundaries to
#'   be overlaid on the raster map (e.g., continents, biogeographic regions, or
#'   study area limits).
#'
#' @return A \code{ggplot2} object is returned.
#'
#' @examples
#' \dontrun{
#'
#' # Compute evoregions
#'
#' akodon_regions <-  Herodotools::calc_evoregions(comm = akodon_pa_tree,
#'                                          phy = akodon_newick)
#'
#' #' #Load data
#'
#' site_xy <- akodon_sites %>%
#'     dplyr::select(LONG, LAT)
#'
#' coastline <- rnaturalearth::ne_coastline(returnclass = "sf")
#'
#' coastline_crop <- sf::st_crop(coastline,
#'                           xmin = map_limits$x[1],
#'                           xmax = map_limits$x[2],
#'                           ymin = map_limits$y[1],
#'                           ymax = map_limits$y[2])
#'
#' plot_evoregions(evoregions = akodon_regions,
#'                  coords = site_xy,
#'                  shapefile = coastline_crop)
#'
#' }
#'
#' @author Maria Gabriela Junqueira and Gabriel Nakamura
#'
#' @export


plot_evoregions <- function(evoregions,
                            coords,
                            shapefile) {


  # ---- checks for sites_xy ----
  if (!is.data.frame(coords)) {
    stop("coords must be a data.frame or tibble with longitude and latitude.")
  }

  if (ncol(coords) < 2) {
    stop("coords must have at least two columns.")
  }

  lon_names <- c("LONG", "lon", "longitude", "x")
  lat_names <- c("LAT", "lat", "latitude", "y")

  col1 <- names(coords)[1]
  col2 <- names(coords)[2]

  if (!col1 %in% lon_names | !col2 %in% lat_names) {
    stop("The first column of coords must be longitude and the second latitude.")
  }

  coords <- dplyr::rename(
    coords,
    LONG = !!col1,
    LAT  = !!col2
  )

  site_region <- evoregions$cluster_evoregions

  df_evoregions <- data.frame(
    coords,
    site_region
  )

  r_evoregions <- terra::rast(df_evoregions)

  sf_evoregions <- terra::as.polygons(r_evoregions) %>%
    sf::st_as_sf()

  sf::st_crs(sf_evoregions) <- sf::st_crs(shapefile)

  ggplot2::ggplot(df_evoregions) +
    ggplot2::geom_raster(
      aes(x = LONG, y = LAT, fill = as.factor(site_region))) +
    rcartocolor::scale_fill_carto_d(
      type = "qualitative",
      palette = "Bold",
      name = "Evoregion") +
    ggplot2::geom_sf(
      data = shapefile,
      fill = NA,
      color = "black",
      linewidth = 0.7) +
    ggplot2::geom_sf(
      data = sf_evoregions,
      color = "#040400",
      fill = NA,
      size = 0.2) +
    ggplot2::theme_bw() +
    ggplot2::xlab("\nLongitude") +
    ggplot2::ylab("Latitude\n") +
    ggplot2::theme(
      panel.grid.major = element_line(linetype = "dashed",lineend = "round"),
      axis.text.y = element_text(angle = 90, hjust = .45),
      axis.title = element_text(size = 12, face = "bold"),
      legend.key.spacing.x = unit(1.5, "mm"),
      legend.key.spacing.y = unit(1.5, "mm"),
    )
}