#' Plot in-situ diversification metrics across geographic space
#'
#' This function creates raster maps of community-level in-situ diversification
#' metrics across geographic space. It allows plotting a single diversification
#' metric or, alternatively, generating three independent maps (Jetz-based,
#' in-situ, and proportional diversification rates).
#'
#' @param insitu_diversification A list generated by
#'   \code{\link[Herodotools]{calc_insitu_diversification}} containing community-level
#'   in-situ diversification metrics. The object must include the elements
#'   \code{jetz_comm_mean}, \code{insitu_comm_mean}, and
#'   \code{prop_comm_mean}, each corresponding to a numeric vector with
#'   diversification values per site.
#'
#' @param coords A rectangular object (it can be a matrix, data.frame or tibble)
#'     containing two columns, one with longitude and another with latitude
#'     coordinates in this order.
#'
#' @param shapefile An \code{sf} object containing the geographic boundaries to
#'   be overlaid on the raster map (e.g., continents, biogeographic regions, or
#'   study area limits).
#'
#' @param variable  character string indicating which diversification metric
#'   should be plotted when \code{facet = FALSE}. Must be one of
#'   \code{"DR_jetz"}, \code{"DR_insitu"}, or \code{"DR_prop"}.
#'
#' @param color_palette character string specifying the color palette to be used for
#'   quantitative variables in \code{rcartocolor::scale_fill_carto_c}. Ignored
#'   for \code{"DR_prop"}, which uses a fixed palette and scale. Default is "SunsetDark"
#'
#' @param facet Logical. If \code{FALSE} (default), a single raster map is
#'   produced for the selected \code{variable}. If \code{TRUE}, three maps
#'   (Jetz-based, in-situ, and proportional diversification rates) are generated
#'   and combined into a single layout, each with an independent color scale. Default is FALSE
#'
#' @return A \code{ggplot2} object if \code{facet = FALSE}. When
#'   \code{facet = TRUE}, a patchwork object combining three \code{ggplot2}
#'   objects is returned.
#'
#' @examples
#' \dontrun{
#'
#' # Compute diversification metrics
#'
#' akodon_diversification <- Herodotools::calc_insitu_diversification(W = akodon_pa_tree,
#'                                       tree = akodon_newick,
#'                                       ancestral.area = node_area,
#'                                       biogeo = biogeo_area,
#'                                       type = "equal.splits")
#' #Load data
#'
#' site_xy <- akodon_sites |>
#'     dplyr::select(LONG, LAT)
#'
#' coastline <- rnaturalearth::ne_coastline(returnclass = "sf")
#'
#' coastline_crop <- sf::st_crop(coastline,
#'                           xmin = map_limits$x[1],
#'                           xmax = map_limits$x[2],
#'                           ymin = map_limits$y[1],
#'                           ymax = map_limits$y[2])
#'
#' #Single map
#'
#' plot_insitu_diversification(insitu_diversification = akodon_diversification,
#'                             coords = site_xy,
#'                             shapefile = coastline_crop,
#'                             variable = "DR_prop")
#'
#' # Three maps with independent color scales
#'
#' plot_insitu_diversification(insitu_diversification = akodon_diversification,
#'                             coords = site_xy,
#'                             shapefile = coastline_crop,
#'                             facet = TRUE)
#' }
#'
#' @author Maria Gabriela Junqueira and Gabriel Nakamura
#'
#' @export

plot_insitu_diversification <- function(insitu_diversification,
                                        coords,
                                        shapefile,
                                        variable = c("DR_jetz", "DR_insitu", "DR_prop"),
                                        color_palette = "SunsetDark",
                                        facet = FALSE) {

  # step 1 - checks for coords ----
  if (!is.data.frame(coords)) {
    stop("coords must be a data.frame or tibble with longitude and latitude.")
  }

  if (ncol(coords) < 2) {
    stop("coords must have at least two columns.")
  }

  lon_names <- c("LONG", "lon", "longitude", "x")
  lat_names <- c("LAT", "lat", "latitude", "y")

  col1 <- names(coords)[1]
  col2 <- names(coords)[2]

  if (!col1 %in% lon_names || !col2 %in% lat_names) {
    stop("The first column of coords must be longitude and the second latitude.")
  }

  coords <- dplyr::rename(
    coords,
    LONG = !!col1,
    LAT  = !!col2
  )

  # step 2 - build dataframe ----
  df_sites <- dplyr::bind_cols(
    coords,
    DR_jetz   = insitu_diversification$jetz_comm_mean,
    DR_insitu = insitu_diversification$insitu_comm_mean,
    DR_prop   = insitu_diversification$prop_comm_mean
  )

  # step 3 - internal plotting function (one variable) ----
  plot_one <- function(var) {

    if (!var %in% c("DR_jetz", "DR_insitu", "DR_prop")) {
      stop("variable must be one of: DR_jetz, DR_insitu, DR_prop")
    }

    legend_title <- switch(
      var,
      DR_jetz   = "Diversification rate (Jetz)",
      DR_insitu = "In-situ diversification rate",
      DR_prop   = "Proportional diversification rate"
    )


    p <- ggplot2::ggplot(df_sites) +
      ggplot2::geom_raster(
        ggplot2::aes(
          x = LONG,
          y = LAT,
          fill = .data[[var]]
        )
      )

    # step 3.1 - scale conditional ----
    if (var == "DR_jetz") {
      fill_scale <- rcartocolor::scale_fill_carto_c(
        type = "quantitative",
        palette = color_palette
      )
    } else {
      fill_scale <- rcartocolor::scale_fill_carto_c(
        type = "quantitative",
        palette = "SunsetDark",
        direction = 1,
        limits = c(0, 1),
        breaks = seq(0, 1, by = 0.25),
        labels = glue::glue("{seq(0, 1, by = 0.25)}")
      )
    }

    p +
      fill_scale +
      ggplot2::geom_sf(
        data = shapefile,
        fill = NA,
        color = "black",
        linewidth = 0.7
      ) +
      ggplot2::guides(
        fill = ggplot2::guide_colorbar(
          barheight = grid::unit(50, "mm"),
          barwidth  = grid::unit(2.5, "mm"),
          direction = "vertical",
          ticks.colour = "#ffffff",
          title.position = "top",
          title.hjust = 0.5
        )
      ) +
      ggplot2::labs(fill = legend_title) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        panel.grid.major = ggplot2::element_line(
          linetype = "dashed",
          lineend = "round"
        ),
        axis.title = ggplot2::element_blank(),
        axis.text.y = ggplot2::element_text(angle = 90, hjust = 0.45)
      )
  }

  # step 4 - output ----
  if (facet) {

    p1 <- plot_one("DR_jetz")

    p1 <- p1 +
      ggplot2::theme(
        legend.position = "top",
        legend.box.margin = ggplot2::margin(0, 0, 0, 0)
      ) &
      ggplot2::guides(
        fill = ggplot2::guide_colorbar(
          barheight = grid::unit(2.5, "mm"),
          barwidth  = grid::unit(50, "mm"),
          direction = "horizontal",
          ticks.colour = "#ffffff",
          title.position = "top",
          title.hjust = 0.5
        )
      )

    p2 <- plot_one("DR_insitu")

    p2 <- p2 +
      ggplot2::theme(
        legend.position = "top",
        legend.box.margin = ggplot2::margin(0, 0, 0, 0)
      ) &
      ggplot2::guides(
        fill = ggplot2::guide_colorbar(
          barheight = grid::unit(2.5, "mm"),
          barwidth  = grid::unit(50, "mm"),
          direction = "horizontal",
          ticks.colour = "#ffffff",
          title.position = "top",
          title.hjust = 0.5
        )
      )

    p3 <- plot_one("DR_prop")

    p3 <- p3 +
      ggplot2::theme(
        legend.position = "top",
        legend.box.margin = ggplot2::margin(0, 0, 0, 0)
      ) &
      ggplot2::guides(
        fill = ggplot2::guide_colorbar(
          barheight = grid::unit(2.5, "mm"),
          barwidth  = grid::unit(50, "mm"),
          direction = "horizontal",
          ticks.colour = "#ffffff",
          title.position = "top",
          title.hjust = 0.5
        )
      )

    p_final <- (p1 | p2 | p3)


    return(p_final)

  } else {

    return(plot_one(variable))
  }

}

